# Generated by Django 3.2.8 on 2021-10-09 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_front', '0002_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsd_front.course')),
            ],
        ),
        migrations.CreateModel(
            name='Learnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsd_front.course')),
            ],
        ),
    ]
