# Generated by Django 3.2.8 on 2021-10-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_front', '0005_auto_20211009_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_avilability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='DEFAULT-IMG.jpg', upload_to='files/courses_thumbnails'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=200), max_length=200),
        ),
    ]
