# Generated by Django 3.2.8 on 2021-10-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_front', '0008_auto_20211009_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Learning',
        ),
        migrations.RenameModel(
            old_name='Prerequisits',
            new_name='Prerequisit',
        ),
        migrations.RenameModel(
            old_name='Learnings',
            new_name='Tag',
        ),
        migrations.AlterField(
            model_name='course',
            name='resources',
            field=models.FileField(upload_to='media/files'),
        ),
    ]
