# Generated by Django 3.2.8 on 2021-10-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_front', '0010_alter_course_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='resources',
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsd_front.course')),
            ],
        ),
    ]
