# Generated by Django 3.2.8 on 2021-10-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_front', '0011_auto_20211009_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='media/files'),
        ),
    ]
