# Generated by Django 3.2.8 on 2021-10-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_front', '0012_alter_resource_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='Name',
            new_name='lecture',
        ),
    ]
