# Generated by Django 3.2.8 on 2021-10-09 09:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_front', '0013_rename_name_resource_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prerequisit',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
