# Generated by Django 3.2.8 on 2021-10-12 07:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_front', '0014_auto_20211009_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='avatar.jpeg', upload_to='media/images')),
                ('name', models.CharField(max_length=255)),
                ('expert_on', models.CharField(max_length=255)),
                ('self_intro', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('personal_bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('career_histroy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('educational_qualifications', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TsdBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='DEFAULT-IMG.jpg', upload_to='media/images')),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='files'),
        ),
    ]
