# Generated by Django 3.2.8 on 2021-10-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_front', '0015_auto_20211012_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsdblog',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=200, null=True), max_length=200),
        ),
        migrations.AddField(
            model_name='tsdblog',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tsdblog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
