# Generated by Django 3.2.8 on 2021-10-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_front', '0017_auto_20211014_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slot_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slot_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
